In [5]:
import pandas as pd

In [6]:
data = pd.read_csv('./edaData/processed_data_120.csv')
data['target_dates'] = pd.to_datetime(data['target_dates'])
data

,datetime,AverageTemperature,City,Country,Latitude,Lag_1_Temp,Lag_2_Temp,Lag_3_Temp,Lag_4_Temp,Lag_5_Temp,...,Roll_3_Avg,Roll_6_Avg,Roll_12_Avg,Roll_24_Avg,Roll_36_Avg,Roll_min_Temp,Roll_max_Temp,Roll_avg_Temp,target_dates,target_AvgTemp
0,1903-01-31,26.098,Abidjan,Côte D'Ivoire,5.63,25.145,25.889,24.590,24.307,23.464,...,25.710667,24.915500,25.551250,25.761458,25.886556,23.464,28.395,25.881405,1913-01-31,27.551
1,1903-02-28,26.682,Abidjan,Côte D'Ivoire,5.63,26.098,25.145,25.889,24.590,24.307,...,25.975000,25.451833,25.493917,25.710167,25.855056,23.464,28.395,25.902474,1913-02-28,27.949
2,1903-03-31,28.107,Abidjan,Côte D'Ivoire,5.63,26.682,26.098,25.145,25.889,24.590,...,26.962333,26.085167,25.517667,25.734958,25.847056,23.464,28.395,25.959000,1913-03-31,27.822
3,1903-04-30,27.139,Abidjan,Côte D'Ivoire,5.63,28.107,26.682,26.098,25.145,25.889,...,27.309333,26.510000,25.560500,25.748417,25.831306,23.464,28.395,25.988500,1913-04-30,27.501
4,1903-05-31,26.066,Abidjan,Côte D'Ivoire,5.63,27.139,28.107,26.682,26.098,25.145,...,27.104000,26.539500,25.521583,25.757958,25.812222,23.464,28.395,25.990390,1913-05-31,25.832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,2002-08-31,23.497,Xian,China,34.56,25.513,24.147,17.176,13.001,9.357,...,24.385667,18.781833,12.708667,12.567917,12.545167,-6.418,26.762,11.637415,2012-08-31,23.885
119996,2002-09-30,18.337,Xian,China,34.56,23.497,25.513,24.147,17.176,13.001,...,22.449000,20.278500,12.786750,12.589333,12.500028,-6.418,26.762,11.642848,2012-09-30,17.028
119997,2002-10-31,12.804,Xian,China,34.56,18.337,23.497,25.513,24.147,17.176,...,18.212667,20.245667,12.798833,12.659667,12.523778,-6.418,26.762,11.643789,2012-10-31,12.399
119998,2002-11-30,6.092,Xian,China,34.56,12.804,18.337,23.497,25.513,24.147,...,12.411000,18.398333,12.807583,12.742875,12.527028,-6.418,26.762,11.639294,2012-11-30,4.736
119999,2002-12-31,-1.590,Xian,China,34.56,6.092,12.804,18.337,23.497,25.513,...,5.768667,14.108833,12.816000,12.623917,12.476611,-6.418,26.762,11.628591,2012-12-31,-0.822

In [8]:
def data_split_generator(data):
    train_start_date = pd.to_datetime('1910-01-31')
    train_end_date = pd.to_datetime('1990-12-31')
    vali_end_date = pd.to_datetime('2000-12-31')
    # test_end_date = pd.to_datetime('2010-12-31')
    for i in range(5):
        # print(train_start_date, train_end_date, vali_end_date, test_end_date)
        train_data = data[(data.target_dates >= train_start_date) & (data.target_dates <= train_end_date)]
        vali_data = data[(data.target_dates > train_end_date) & (data.target_dates <= vali_end_date)]
        # test_data = data[(data.target_dates > vali_end_date) & (data.target_dates <= test_end_date)]
        yield train_data, vali_data
        # print(train_data.shape, vali_data.shape, test_data.shape)
        train_end_date = train_end_date + pd.DateOffset(years = -10) + pd.offsets.MonthEnd(0)
        vali_end_date = vali_end_date + pd.DateOffset(years = -10) + pd.offsets.MonthEnd(0)
        # test_end_date = test_end_date + pd.DateOffset(years = -10) + pd.offsets.MonthEnd(0)
data_split = data_split_generator(data)

In [9]:
for j in range(120, 133):
    data = pd.read_csv(f'./edaData/processed_data_{j}.csv')
    data['target_dates'] = pd.to_datetime(data['target_dates'])
    data_split = data_split_generator(data)
    for i in range(5):
        train_data, vali_data = next(data_split)
        # model
        #
train_data

,datetime,AverageTemperature,City,Country,Latitude,Lag_1_Temp,Lag_2_Temp,Lag_3_Temp,Lag_4_Temp,Lag_5_Temp,...,Roll_3_Avg,Roll_6_Avg,Roll_12_Avg,Roll_24_Avg,Roll_36_Avg,Roll_min_Temp,Roll_max_Temp,Roll_avg_Temp,target_dates,target_AvgTemp
0,1903-01-31,26.098,Abidjan,Côte D'Ivoire,5.63,25.145,25.889,24.590,24.307,23.464,...,25.710667,24.915500,25.551250,25.761458,25.886556,23.464,28.395,25.881405,1914-01-31,26.752
1,1903-02-28,26.682,Abidjan,Côte D'Ivoire,5.63,26.098,25.145,25.889,24.590,24.307,...,25.975000,25.451833,25.493917,25.710167,25.855056,23.464,28.395,25.902474,1914-02-28,28.123
2,1903-03-31,28.107,Abidjan,Côte D'Ivoire,5.63,26.682,26.098,25.145,25.889,24.590,...,26.962333,26.085167,25.517667,25.734958,25.847056,23.464,28.395,25.959000,1914-03-31,28.123
3,1903-04-30,27.139,Abidjan,Côte D'Ivoire,5.63,28.107,26.682,26.098,25.145,25.889,...,27.309333,26.510000,25.560500,25.748417,25.831306,23.464,28.395,25.988500,1914-04-30,28.048
4,1903-05-31,26.066,Abidjan,Côte D'Ivoire,5.63,27.139,28.107,26.682,26.098,25.145,...,27.104000,26.539500,25.521583,25.757958,25.812222,23.464,28.395,25.990390,1914-05-31,26.856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118051,1939-08-31,24.882,Xian,China,34.56,25.067,22.927,19.075,11.223,6.980,...,24.292000,18.359000,12.168917,11.887458,11.842861,-6.418,26.762,11.423256,1950-08-31,23.455
118052,1939-09-30,18.371,Xian,China,34.56,24.882,25.067,22.927,19.075,11.223,...,22.773333,20.257500,12.310167,11.950167,11.829722,-6.418,26.762,11.437822,1950-09-30,17.188
118053,1939-10-31,12.772,Xian,China,34.56,18.371,24.882,25.067,22.927,19.075,...,18.675000,20.515667,12.330167,11.979375,11.812083,-6.418,26.762,11.440613,1950-10-31,10.961
118054,1939-11-30,4.299,Xian,China,34.56,12.772,18.371,24.882,25.067,22.927,...,11.814000,18.053000,12.182417,12.012000,11.772417,-6.418,26.762,11.425704,1950-11-30,4.515
118055,1939-12-31,-0.463,Xian,China,34.56,4.299,12.772,18.371,24.882,25.067,...,5.536000,14.154667,12.161250,11.971000,11.817417,-6.418,26.762,11.400935,1950-12-31,-2.209